apiVersion: batch/v1
kind: CronJob
metadata:
  name: manoj
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - image: ubuntu
            name: manoj
            command: ["/bin/bash", "-c", "echo vishnoi; sleep 5"]
          restartPolicy: Never
